AWSTemplateFormatVersion: "2010-09-09"
Description: "Lamp template for Multiple Environments defined in Parameters"

Parameters:
  vpcCidrBase:
    Type: String
    # Default: '10.1.'
  subnetStart:
    Type: String
    # Default: '1'
  env:
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:
  wpvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        !Join
          - ''
          - - !Ref vpcCidrBase
            - !Ref subnetStart
            - '.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: app
         Value: wordpress
       - Key: Name
         Value:
          !Join
            - ''
            - - LAMP
              - 'VPC'
              - !Ref env
